version: '2'
services:
  ods:
    image: mojo-docker.cs.fau.de/osrg_ods_public/ods:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - COUCHDB_MAX_CONNECTIONS=100
      - ODS_ADMIN_CONTEXT_PATH=/
      - ODS_CONTEXT_PATH=/ods
      - ODS_ADMIN_PASSWORD=admin123
      - COUCHDB_URL=http://couchdb:5984/
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
